
[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "0.6.0"

[[constraint]]
  name = "github.com/containernetworking/plugins"
  version = "0.6.0"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "15.0.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.5.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/orcaman/concurrent-map"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/vishvananda/netlink"

[[constraint]]
  name = "github.com/yunify/qingcloud-sdk-go"
  version = "2.0.0-alpha.9"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.2"
