apiVersion: v1
kind: ServiceAccount
metadata:
  name: hostnic
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: qingcloud-hostnic-daemon
  namespace: kube-system
  labels:
    k8s-app: kube-qingcloud-hostnic
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: kube-qingcloud-hostnic
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: kube-qingcloud-hostnic
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        beta.kubernetes.io/os: "linux"
      hostNetwork: true
      serviceAccountName: hostnic
      containers:
      - name: qingcloud-hostnic-daemon
        image: dockerhub.qingcloud.com/qingcloud/hostnic-cni:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: LOGLEVEL
          value: "info"

        - name: VXNETS
          value: "vxnet-xxxxxxx vxnet-xxxxxxx"

        - name: POOLSIZE
          value: "3"

        volumeMounts:
        - name: qingcloud-cfg
          mountPath: /etc/qingcloud/
      volumes:
      - name: qingcloud-cfg
        hostPath:
          path: /etc/qingcloud/
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "dedicated"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        effect: NoSchedule
    - key: node.cloudprovider.kubernetes.io/uninitialized
      effect: NoSchedule
      value: "true"
