// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.11.2
// source: pkg/rpc/message.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CNIBackend_AddNetwork_FullMethodName = "/rpc.CNIBackend/AddNetwork"
	CNIBackend_DelNetwork_FullMethodName = "/rpc.CNIBackend/DelNetwork"
	CNIBackend_ShowNics_FullMethodName   = "/rpc.CNIBackend/ShowNics"
	CNIBackend_ClearNics_FullMethodName  = "/rpc.CNIBackend/ClearNics"
)

// CNIBackendClient is the client API for CNIBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CNIBackendClient interface {
	AddNetwork(ctx context.Context, in *IPAMMessage, opts ...grpc.CallOption) (*IPAMMessage, error)
	DelNetwork(ctx context.Context, in *IPAMMessage, opts ...grpc.CallOption) (*IPAMMessage, error)
	ShowNics(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*NicInfoList, error)
	ClearNics(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Nothing, error)
}

type cNIBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewCNIBackendClient(cc grpc.ClientConnInterface) CNIBackendClient {
	return &cNIBackendClient{cc}
}

func (c *cNIBackendClient) AddNetwork(ctx context.Context, in *IPAMMessage, opts ...grpc.CallOption) (*IPAMMessage, error) {
	out := new(IPAMMessage)
	err := c.cc.Invoke(ctx, CNIBackend_AddNetwork_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cNIBackendClient) DelNetwork(ctx context.Context, in *IPAMMessage, opts ...grpc.CallOption) (*IPAMMessage, error) {
	out := new(IPAMMessage)
	err := c.cc.Invoke(ctx, CNIBackend_DelNetwork_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cNIBackendClient) ShowNics(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*NicInfoList, error) {
	out := new(NicInfoList)
	err := c.cc.Invoke(ctx, CNIBackend_ShowNics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cNIBackendClient) ClearNics(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, CNIBackend_ClearNics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CNIBackendServer is the server API for CNIBackend service.
// All implementations should embed UnimplementedCNIBackendServer
// for forward compatibility
type CNIBackendServer interface {
	AddNetwork(context.Context, *IPAMMessage) (*IPAMMessage, error)
	DelNetwork(context.Context, *IPAMMessage) (*IPAMMessage, error)
	ShowNics(context.Context, *Nothing) (*NicInfoList, error)
	ClearNics(context.Context, *Nothing) (*Nothing, error)
}

// UnimplementedCNIBackendServer should be embedded to have forward compatible implementations.
type UnimplementedCNIBackendServer struct {
}

func (UnimplementedCNIBackendServer) AddNetwork(context.Context, *IPAMMessage) (*IPAMMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNetwork not implemented")
}
func (UnimplementedCNIBackendServer) DelNetwork(context.Context, *IPAMMessage) (*IPAMMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelNetwork not implemented")
}
func (UnimplementedCNIBackendServer) ShowNics(context.Context, *Nothing) (*NicInfoList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowNics not implemented")
}
func (UnimplementedCNIBackendServer) ClearNics(context.Context, *Nothing) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearNics not implemented")
}

// UnsafeCNIBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CNIBackendServer will
// result in compilation errors.
type UnsafeCNIBackendServer interface {
	mustEmbedUnimplementedCNIBackendServer()
}

func RegisterCNIBackendServer(s grpc.ServiceRegistrar, srv CNIBackendServer) {
	s.RegisterService(&CNIBackend_ServiceDesc, srv)
}

func _CNIBackend_AddNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPAMMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIBackendServer).AddNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNIBackend_AddNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIBackendServer).AddNetwork(ctx, req.(*IPAMMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _CNIBackend_DelNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IPAMMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIBackendServer).DelNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNIBackend_DelNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIBackendServer).DelNetwork(ctx, req.(*IPAMMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _CNIBackend_ShowNics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIBackendServer).ShowNics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNIBackend_ShowNics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIBackendServer).ShowNics(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _CNIBackend_ClearNics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIBackendServer).ClearNics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNIBackend_ClearNics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIBackendServer).ClearNics(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

// CNIBackend_ServiceDesc is the grpc.ServiceDesc for CNIBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CNIBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.CNIBackend",
	HandlerType: (*CNIBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNetwork",
			Handler:    _CNIBackend_AddNetwork_Handler,
		},
		{
			MethodName: "DelNetwork",
			Handler:    _CNIBackend_DelNetwork_Handler,
		},
		{
			MethodName: "ShowNics",
			Handler:    _CNIBackend_ShowNics_Handler,
		},
		{
			MethodName: "ClearNics",
			Handler:    _CNIBackend_ClearNics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/rpc/message.proto",
}
