/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/yunify/hostnic-cni/pkg/apis/vxnet/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVxNetPools implements VxNetPoolInterface
type FakeVxNetPools struct {
	Fake *FakeVxnetV1alpha1
}

var vxnetpoolsResource = schema.GroupVersionResource{Group: "vxnet.qingcloud.com", Version: "v1alpha1", Resource: "vxnetpools"}

var vxnetpoolsKind = schema.GroupVersionKind{Group: "vxnet.qingcloud.com", Version: "v1alpha1", Kind: "VxNetPool"}

// Get takes name of the vxNetPool, and returns the corresponding vxNetPool object, and an error if there is any.
func (c *FakeVxNetPools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VxNetPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(vxnetpoolsResource, name), &v1alpha1.VxNetPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VxNetPool), err
}

// List takes label and field selectors, and returns the list of VxNetPools that match those selectors.
func (c *FakeVxNetPools) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VxNetPoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(vxnetpoolsResource, vxnetpoolsKind, opts), &v1alpha1.VxNetPoolList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VxNetPoolList{ListMeta: obj.(*v1alpha1.VxNetPoolList).ListMeta}
	for _, item := range obj.(*v1alpha1.VxNetPoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vxNetPools.
func (c *FakeVxNetPools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(vxnetpoolsResource, opts))
}

// Create takes the representation of a vxNetPool and creates it.  Returns the server's representation of the vxNetPool, and an error, if there is any.
func (c *FakeVxNetPools) Create(ctx context.Context, vxNetPool *v1alpha1.VxNetPool, opts v1.CreateOptions) (result *v1alpha1.VxNetPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(vxnetpoolsResource, vxNetPool), &v1alpha1.VxNetPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VxNetPool), err
}

// Update takes the representation of a vxNetPool and updates it. Returns the server's representation of the vxNetPool, and an error, if there is any.
func (c *FakeVxNetPools) Update(ctx context.Context, vxNetPool *v1alpha1.VxNetPool, opts v1.UpdateOptions) (result *v1alpha1.VxNetPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(vxnetpoolsResource, vxNetPool), &v1alpha1.VxNetPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VxNetPool), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVxNetPools) UpdateStatus(ctx context.Context, vxNetPool *v1alpha1.VxNetPool, opts v1.UpdateOptions) (*v1alpha1.VxNetPool, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(vxnetpoolsResource, "status", vxNetPool), &v1alpha1.VxNetPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VxNetPool), err
}

// Delete takes name of the vxNetPool and deletes it. Returns an error if one occurs.
func (c *FakeVxNetPools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(vxnetpoolsResource, name), &v1alpha1.VxNetPool{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVxNetPools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(vxnetpoolsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VxNetPoolList{})
	return err
}

// Patch applies the patch and returns the patched vxNetPool.
func (c *FakeVxNetPools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VxNetPool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(vxnetpoolsResource, name, pt, data, subresources...), &v1alpha1.VxNetPool{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VxNetPool), err
}
