/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/yunify/hostnic-cni/pkg/apis/vxnet/v1alpha1"
	scheme "github.com/yunify/hostnic-cni/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VxNetPoolsGetter has a method to return a VxNetPoolInterface.
// A group's client should implement this interface.
type VxNetPoolsGetter interface {
	VxNetPools() VxNetPoolInterface
}

// VxNetPoolInterface has methods to work with VxNetPool resources.
type VxNetPoolInterface interface {
	Create(ctx context.Context, vxNetPool *v1alpha1.VxNetPool, opts v1.CreateOptions) (*v1alpha1.VxNetPool, error)
	Update(ctx context.Context, vxNetPool *v1alpha1.VxNetPool, opts v1.UpdateOptions) (*v1alpha1.VxNetPool, error)
	UpdateStatus(ctx context.Context, vxNetPool *v1alpha1.VxNetPool, opts v1.UpdateOptions) (*v1alpha1.VxNetPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VxNetPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VxNetPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VxNetPool, err error)
	VxNetPoolExpansion
}

// vxNetPools implements VxNetPoolInterface
type vxNetPools struct {
	client rest.Interface
}

// newVxNetPools returns a VxNetPools
func newVxNetPools(c *VxnetV1alpha1Client) *vxNetPools {
	return &vxNetPools{
		client: c.RESTClient(),
	}
}

// Get takes name of the vxNetPool, and returns the corresponding vxNetPool object, and an error if there is any.
func (c *vxNetPools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VxNetPool, err error) {
	result = &v1alpha1.VxNetPool{}
	err = c.client.Get().
		Resource("vxnetpools").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VxNetPools that match those selectors.
func (c *vxNetPools) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VxNetPoolList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VxNetPoolList{}
	err = c.client.Get().
		Resource("vxnetpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vxNetPools.
func (c *vxNetPools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("vxnetpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vxNetPool and creates it.  Returns the server's representation of the vxNetPool, and an error, if there is any.
func (c *vxNetPools) Create(ctx context.Context, vxNetPool *v1alpha1.VxNetPool, opts v1.CreateOptions) (result *v1alpha1.VxNetPool, err error) {
	result = &v1alpha1.VxNetPool{}
	err = c.client.Post().
		Resource("vxnetpools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vxNetPool).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vxNetPool and updates it. Returns the server's representation of the vxNetPool, and an error, if there is any.
func (c *vxNetPools) Update(ctx context.Context, vxNetPool *v1alpha1.VxNetPool, opts v1.UpdateOptions) (result *v1alpha1.VxNetPool, err error) {
	result = &v1alpha1.VxNetPool{}
	err = c.client.Put().
		Resource("vxnetpools").
		Name(vxNetPool.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vxNetPool).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vxNetPools) UpdateStatus(ctx context.Context, vxNetPool *v1alpha1.VxNetPool, opts v1.UpdateOptions) (result *v1alpha1.VxNetPool, err error) {
	result = &v1alpha1.VxNetPool{}
	err = c.client.Put().
		Resource("vxnetpools").
		Name(vxNetPool.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vxNetPool).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vxNetPool and deletes it. Returns an error if one occurs.
func (c *vxNetPools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("vxnetpools").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vxNetPools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("vxnetpools").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vxNetPool.
func (c *vxNetPools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VxNetPool, err error) {
	result = &v1alpha1.VxNetPool{}
	err = c.client.Patch(pt).
		Resource("vxnetpools").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
